"""
Módulo: schemas.py
Descrição: Define os Data Transfer Objects (DTOs) e as lógicas de validação de dados.
Contém as classes que validam estruturalmente os payloads JSON recebidos (Requests) 
e formatam os dados de saída (Responses). Garante que o serviço respeite rigorosamente 
as tipagens e campos exigidos no contrato OpenAPI (api-docs.yaml).
"""
# Arquivo gerado automaticamente a partir do contrato OpenAPI (api-docs.yaml) usando a ferramenta datamodel-codegen.
# generated by datamodel-codegen:
#   filename:  api-docs.yaml
#   timestamp: 2026-06-02T18:50:05+00:00

from __future__ import annotations

from enum import Enum

from pydantic import AwareDatetime, BaseModel, Field, confloat, constr

# ==========================================
# Classes Gerais (usadas por todos)
# ==========================================
class ErrorResponse(BaseModel):
    timestamp: AwareDatetime = Field(..., examples=['2026-05-19T13:00:00Z'])
    status: int = Field(..., examples=[400])
    error: str = Field(..., examples=['Bad Request'])
    message: str = Field(..., examples=['Campo obrigatório ausente.'])
    path: str = Field(..., examples=['/api/participation/quotas'])


class PageMetadata(BaseModel):
    page: int = Field(..., examples=[0])
    size: int = Field(..., examples=[20])
    totalElements: int = Field(..., examples=[42])
    totalPages: int = Field(..., examples=[3])

# ==========================================
# Domínio de Cotas (Quotas)
# ==========================================
class QuotaCondition(Enum):
    DAILY = 'DAILY'
    SPORADIC = 'SPORADIC'


class QuotaItems(Enum):
    ALL = 'ALL'
    COFFEE = 'COFFEE'
    COOKIES = 'COOKIES'


class ParticipationQuotaStatus(Enum):
    ACTIVE = 'ACTIVE'
    INACTIVE = 'INACTIVE'


class CreateParticipationQuotaRequest(BaseModel):
    name: str = Field(..., examples=['Cota diária completa'])
    description: str | None = Field(
        None, examples=['Participante diário com acesso a café e bolachas.']
    )
    condition: QuotaCondition
    items: QuotaItems
    amount: confloat(ge=0.0) = Field(
        ...,
        description='Valor definido pelo gestor. O serviço não calcula este valor automaticamente.',
        examples=[40.0],
    )
    active: bool | None = True


class UpdateParticipationQuotaRequest(BaseModel):
    name: str | None = None
    description: str | None = None
    condition: QuotaCondition | None = None
    items: QuotaItems | None = None
    amount: confloat(ge=0.0) | None = None
    active: bool | None = None


class ParticipationQuota(BaseModel):
    id: str = Field(..., examples=['quota_001'])
    name: str = Field(..., examples=['Cota diária completa'])
    description: str | None = Field(
        None, examples=['Participante diário com acesso a café e bolachas.']
    )
    condition: QuotaCondition
    items: QuotaItems
    amount: float = Field(..., examples=[40.0])
    status: ParticipationQuotaStatus
    createdBy: str = Field(..., examples=['usr_manager_001'])
    createdAt: AwareDatetime = Field(..., examples=['2026-05-01T08:00:00Z'])
    updatedAt: AwareDatetime | None = None


class ParticipationQuotaPage(BaseModel):
    items: list[ParticipationQuota]
    page: PageMetadata

# ==========================================
# Domínio de Adesões (Participations)
# ==========================================
class ParticipationStatus(Enum):
    ACTIVE = 'ACTIVE'
    CANCELLED = 'CANCELLED'


class JoinParticipationQuotaRequest(BaseModel):
    userId: str = Field(..., examples=['usr_123'])
    quotaId: str = Field(..., examples=['quota_001'])
    startCycle: constr(pattern=r'^\d{4}-\d{2}$') = Field(..., examples=['2026-05'])


class CancelParticipationRequest(BaseModel):
    requestedBy: str = Field(..., examples=['usr_123'])
    reason: str = Field(..., examples=['Participante deixou de usar a copa.'])
    effectiveCycle: constr(pattern=r'^\d{4}-\d{2}$') = Field(
        ..., examples=['2026-06']
    )


class QuotaSnapshot(BaseModel):
    quotaId: str = Field(..., examples=['quota_001'])
    name: str = Field(..., examples=['Cota diária completa'])
    condition: QuotaCondition
    items: QuotaItems
    amount: float = Field(..., examples=[40.0])

class Participation(BaseModel):
    id: str = Field(..., examples=['part_001'])
    userId: str = Field(..., examples=['usr_123'])
    quotaId: str = Field(..., examples=['quota_001'])
    status: ParticipationStatus
    startCycle: constr(pattern=r'^\\d{4}-\\d{2}$') = Field(..., examples=['2026-05'])
    endCycle: constr(pattern=r'^\\d{4}-\\d{2}$') | None = None
    quotaSnapshot: QuotaSnapshot
    createdAt: AwareDatetime = Field(..., examples=['2026-05-02T10:00:00Z'])
    cancelledAt: AwareDatetime | None = None


class ParticipationPage(BaseModel):
    items: list[Participation]
    page: PageMetadata
