"""
Módulo: schemas.py
Descrição: Define os Data Transfer Objects (DTOs) e as lógicas de validação de dados.
Contém as classes que validam estruturalmente os payloads JSON recebidos (Requests) 
e formatam os dados de saída (Responses). Garante que o serviço respeite rigorosamente 
as tipagens e campos exigidos no contrato OpenAPI (api-docs.yaml).
"""
# Arquivo gerado automaticamente a partir do contrato OpenAPI (api-docs.yaml) usando a ferramenta datamodel-codegen.
# generated by datamodel-codegen:
#   filename:  api-docs.yaml
#   timestamp: 2026-06-02T18:50:05+00:00

# TODO EQUIPE: limpar o arquivo e deixar somente os padrões que iremos utilizar:
# Classes Gerais (usadas por todos):
    # ErrorResponse
    # PageMetadata
# Domínio de Cotas (Quotas):
    # QuotaCondition
    # QuotaItems
    # ParticipationQuotaStatus
    # CreateParticipationQuotaRequest
    # UpdateParticipationQuotaRequest
    # ParticipationQuota
    # ParticipationQuotaPage
# Domínio de Adesões (Participations):
    # ParticipationStatus
    # JoinParticipationQuotaRequest
    # CancelParticipationRequest
    # QuotaSnapshot
    # Participation
    # ParticipationPage

from __future__ import annotations

from datetime import date
from enum import Enum

from pydantic import AnyUrl, AwareDatetime, BaseModel, EmailStr, Field, confloat, constr


class ErrorResponse(BaseModel):
    timestamp: AwareDatetime = Field(..., examples=['2026-05-19T13:00:00Z'])
    status: int = Field(..., examples=[400])
    error: str = Field(..., examples=['Bad Request'])
    message: str = Field(..., examples=['Campo obrigatório ausente.'])
    path: str = Field(..., examples=['/api/participation/quotas'])


class PageMetadata(BaseModel):
    page: int = Field(..., examples=[0])
    size: int = Field(..., examples=[20])
    totalElements: int = Field(..., examples=[42])
    totalPages: int = Field(..., examples=[3])


class UserRole(Enum):
    MANAGER = 'MANAGER'
    PARTICIPANT = 'PARTICIPANT'


class UserStatus(Enum):
    ACTIVE = 'ACTIVE'
    INACTIVE = 'INACTIVE'


class CreateUserRequest(BaseModel):
    name: constr(min_length=3) = Field(..., examples=['Maria Silva'])
    email: EmailStr = Field(..., examples=['maria.silva@departamento.edu.br'])
    roles: list[UserRole] | None = ['PARTICIPANT']


class UpdateUserRequest(BaseModel):
    name: constr(min_length=3) | None = None


class DeactivateUserRequest(BaseModel):
    reason: constr(min_length=3) = Field(
        ..., examples=['Usuário não participa mais da copa']
    )


class ReplaceUserRolesRequest(BaseModel):
    roles: list[UserRole] = Field(..., min_length=1)


class User(BaseModel):
    id: str = Field(..., examples=['usr_123'])
    name: str = Field(..., examples=['Maria Silva'])
    email: EmailStr = Field(..., examples=['maria.silva@departamento.edu.br'])
    status: UserStatus
    roles: list[UserRole]
    createdAt: AwareDatetime = Field(..., examples=['2026-05-19T13:00:00Z'])
    updatedAt: AwareDatetime | None = None
    deactivatedAt: AwareDatetime | None = None


class UserPage(BaseModel):
    items: list[User]
    page: PageMetadata


class QuotaCondition(Enum):
    DAILY = 'DAILY'
    SPORADIC = 'SPORADIC'


class QuotaItems(Enum):
    ALL = 'ALL'
    COFFEE = 'COFFEE'
    COOKIES = 'COOKIES'


class ParticipationQuotaStatus(Enum):
    ACTIVE = 'ACTIVE'
    INACTIVE = 'INACTIVE'


class CreateParticipationQuotaRequest(BaseModel):
    name: str = Field(..., examples=['Cota diária completa'])
    description: str | None = Field(
        None, examples=['Participante diário com acesso a café e bolachas.']
    )
    condition: QuotaCondition
    items: QuotaItems
    amount: confloat(ge=0.0) = Field(
        ...,
        description='Valor definido pelo gestor. O serviço não calcula este valor automaticamente.',
        examples=[40.0],
    )
    active: bool | None = True


class UpdateParticipationQuotaRequest(BaseModel):
    name: str | None = None
    description: str | None = None
    condition: QuotaCondition | None = None
    items: QuotaItems | None = None
    amount: confloat(ge=0.0) | None = None
    active: bool | None = None


class ParticipationQuota(BaseModel):
    id: str = Field(..., examples=['quota_001'])
    name: str = Field(..., examples=['Cota diária completa'])
    description: str | None = Field(
        None, examples=['Participante diário com acesso a café e bolachas.']
    )
    condition: QuotaCondition
    items: QuotaItems
    amount: float = Field(..., examples=[40.0])
    status: ParticipationQuotaStatus
    createdBy: str = Field(..., examples=['usr_manager_001'])
    createdAt: AwareDatetime = Field(..., examples=['2026-05-01T08:00:00Z'])
    updatedAt: AwareDatetime | None = None


class ParticipationQuotaPage(BaseModel):
    items: list[ParticipationQuota]
    page: PageMetadata


class ParticipationStatus(Enum):
    ACTIVE = 'ACTIVE'
    CANCELLED = 'CANCELLED'


class JoinParticipationQuotaRequest(BaseModel):
    userId: str = Field(..., examples=['usr_123'])
    quotaId: str = Field(..., examples=['quota_001'])
    startCycle: constr(pattern=r'^\\d{4}-\\d{2}$') = Field(..., examples=['2026-05'])


class CancelParticipationRequest(BaseModel):
    requestedBy: str = Field(..., examples=['usr_123'])
    reason: str = Field(..., examples=['Participante deixou de usar a copa.'])
    effectiveCycle: constr(pattern=r'^\\d{4}-\\d{2}$') = Field(
        ..., examples=['2026-06']
    )


class QuotaSnapshot(BaseModel):
    quotaId: str = Field(..., examples=['quota_001'])
    name: str = Field(..., examples=['Cota diária completa'])
    condition: QuotaCondition
    items: QuotaItems
    amount: float = Field(..., examples=[40.0])


class PendencyStatus(Enum):
    PENDING = 'PENDING'
    WAITING_VALIDATION = 'WAITING_VALIDATION'
    PAID = 'PAID'
    REJECTED = 'REJECTED'
    CANCELLED = 'CANCELLED'


class PendencySource(Enum):
    MONTHLY_PARTICIPATION = 'MONTHLY_PARTICIPATION'


class Pendency(BaseModel):
    id: str = Field(..., examples=['pend_001'])
    source: PendencySource
    sourceId: str = Field(
        ...,
        description='Identificador do registro de origem que gerou a pendência.',
        examples=['mpart_001'],
    )
    userId: str = Field(..., examples=['usr_123'])
    cycle: constr(pattern=r'^\\d{4}-\\d{2}$') = Field(..., examples=['2026-05'])
    amount: float = Field(..., examples=[40.0])
    status: PendencyStatus
    description: str = Field(..., examples=['Cota diária completa - Maio/2026'])
    createdAt: AwareDatetime = Field(..., examples=['2026-05-01T08:10:00Z'])
    paidAt: AwareDatetime | None = None


class PendencyPage(BaseModel):
    items: list[Pendency]
    page: PageMetadata


class PaymentMethod(Enum):
    PIX = 'PIX'
    CASH = 'CASH'
    BANK_TRANSFER = 'BANK_TRANSFER'
    OTHER = 'OTHER'


class PaymentProofStatus(Enum):
    WAITING_VALIDATION = 'WAITING_VALIDATION'
    VALIDATED = 'VALIDATED'
    REJECTED = 'REJECTED'


class SubmitPaymentProofRequest(BaseModel):
    submittedBy: str = Field(..., examples=['usr_123'])
    amount: confloat(ge=0.0) = Field(..., examples=[40.0])
    paymentDate: date = Field(..., examples=['2026-05-10'])
    method: PaymentMethod
    receiptUrl: AnyUrl = Field(
        ..., examples=['https://storage.example.com/receipts/abc123.pdf']
    )
    note: str | None = Field(
        None, examples=['Pagamento referente à cota diária completa de maio.']
    )


class PaymentProofDecisionStatus(Enum):
    VALIDATED = 'VALIDATED'
    REJECTED = 'REJECTED'


class PaymentProofDecisionRequest(BaseModel):
    status: PaymentProofDecisionStatus
    decidedBy: str = Field(..., examples=['usr_manager_001'])
    note: str | None = Field(None, examples=['Comprovante conferido na conta da copa.'])
    reason: str | None = Field(
        None,
        description='Obrigatório quando status for REJECTED.',
        examples=['Valor informado não corresponde à pendência.'],
    )


class PaymentProof(BaseModel):
    id: str = Field(..., examples=['proof_001'])
    pendencyId: str = Field(..., examples=['pend_001'])
    userId: str = Field(..., examples=['usr_123'])
    amount: float = Field(..., examples=[40.0])
    paymentDate: date = Field(..., examples=['2026-05-10'])
    method: PaymentMethod
    receiptUrl: AnyUrl = Field(
        ..., examples=['https://storage.example.com/receipts/abc123.pdf']
    )
    status: PaymentProofStatus
    note: str | None = None
    submittedAt: AwareDatetime = Field(..., examples=['2026-05-10T12:00:00Z'])
    validatedBy: str | None = None
    validatedAt: AwareDatetime | None = None
    rejectedBy: str | None = None
    rejectedAt: AwareDatetime | None = None
    rejectionReason: str | None = None


class PendencyPaymentProofPage(BaseModel):
    items: list[PaymentProof]
    page: PageMetadata


class ExpenseCategory(Enum):
    COFFEE = 'COFFEE'
    TEA = 'TEA'
    COOKIES = 'COOKIES'
    SUGAR = 'SUGAR'
    CUPS = 'CUPS'
    MACHINE_MAINTENANCE = 'MACHINE_MAINTENANCE'
    CLEANING_SUPPLIES = 'CLEANING_SUPPLIES'
    OTHER = 'OTHER'


class ExpenseStatus(Enum):
    REGISTERED = 'REGISTERED'
    CANCELLED = 'CANCELLED'


class CreateExpenseRequest(BaseModel):
    description: str = Field(..., examples=['Compra de café em grãos'])
    category: ExpenseCategory
    amount: confloat(ge=0.0) = Field(..., examples=[85.9])
    expenseDate: date = Field(..., examples=['2026-05-08'])
    registeredBy: str = Field(..., examples=['usr_manager_001'])
    receiptUrl: AnyUrl | None = Field(
        None, examples=['https://storage.example.com/expenses/coffee-receipt.pdf']
    )


class Expense(BaseModel):
    id: str = Field(..., examples=['exp_001'])
    description: str = Field(..., examples=['Compra de café em grãos'])
    category: ExpenseCategory
    amount: float = Field(..., examples=[85.9])
    expenseDate: date = Field(..., examples=['2026-05-08'])
    cycle: constr(pattern=r'^\\d{4}-\\d{2}$') | None = Field(None, examples=['2026-05'])
    status: ExpenseStatus
    registeredBy: str = Field(..., examples=['usr_manager_001'])
    receiptUrl: AnyUrl | None = None
    createdAt: AwareDatetime = Field(..., examples=['2026-05-08T15:00:00Z'])


class ExpensePage(BaseModel):
    items: list[Expense]
    page: PageMetadata


class StatementEntryType(Enum):
    INCOME = 'INCOME'
    EXPENSE = 'EXPENSE'


class StatementEntry(BaseModel):
    id: str = Field(..., examples=['proof_001'])
    type: StatementEntryType
    description: str = Field(
        ..., examples=['Pagamento validado da cota diaria completa']
    )
    amount: confloat(ge=0.0) = Field(..., examples=[40.0])
    occurredAt: AwareDatetime = Field(..., examples=['2026-05-11T09:00:00Z'])
    referenceType: str | None = Field(None, examples=['PAYMENT_PROOF'])
    referenceId: str | None = Field(None, examples=['proof_001'])


class Period(BaseModel):
    startDate: date = Field(..., examples=['2026-05-01'])
    endDate: date = Field(..., examples=['2026-05-31'])


class FinanceStatement(BaseModel):
    period: Period
    totalIncome: float = Field(..., examples=[520.0])
    totalExpense: float = Field(..., examples=[185.9])
    balance: float = Field(..., examples=[334.1])
    entries: list[StatementEntry]


class FinanceBalance(BaseModel):
    totalIncome: float = Field(..., examples=[12450.0])
    totalExpense: float = Field(..., examples=[9780.4])
    balance: float = Field(..., examples=[2669.6])
    updatedAt: AwareDatetime = Field(..., examples=['2026-05-19T18:00:00Z'])


class Participation(BaseModel):
    id: str = Field(..., examples=['part_001'])
    userId: str = Field(..., examples=['usr_123'])
    quotaId: str = Field(..., examples=['quota_001'])
    status: ParticipationStatus
    startCycle: constr(pattern=r'^\\d{4}-\\d{2}$') = Field(..., examples=['2026-05'])
    endCycle: constr(pattern=r'^\\d{4}-\\d{2}$') | None = None
    quotaSnapshot: QuotaSnapshot
    createdAt: AwareDatetime = Field(..., examples=['2026-05-02T10:00:00Z'])
    cancelledAt: AwareDatetime | None = None


class ParticipationPage(BaseModel):
    items: list[Participation]
    page: PageMetadata
